// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Command as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCommand(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCommand;
