// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Flag as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconFlag(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconFlag;
