// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Wind as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconWind(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconWind;
