// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { DownloadCloud as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconDownloadCloud(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconDownloadCloud;
