// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Hash as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconHash(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconHash;
