// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ChevronsRight as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconChevronsRight(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconChevronsRight;
