// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Chrome as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconChrome(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconChrome;
