// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Home as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconHome(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconHome;
