import type { Comic, Item } from '@/types/comic';

export const COMICS: Comic[] = [
  {
    id: 1,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Cape',
    viewsCount: 0,
    image: '/img/comics/page/1.webp',
    thumbnail: '/img/comics/thumbnail/1.webp',
  },
  {
    id: 2,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Halo',
    viewsCount: 0,
    image: '/img/comics/page/2.webp',
    thumbnail: '/img/comics/thumbnail/2.webp',
  },
  {
    id: 3,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Diamond Bat',
    viewsCount: 0,
    image: '/img/comics/page/3.webp',
    thumbnail: '/img/comics/thumbnail/3.webp',
  },
  {
    id: 4,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Bread Bat',
    viewsCount: 0,
    image: '/img/comics/page/4.webp',
    thumbnail: '/img/comics/thumbnail/4.webp',
  },
  {
    id: 5,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Purple Bat',
    viewsCount: 0,
    image: '/img/comics/page/5.webp',
    thumbnail: '/img/comics/thumbnail/5.webp',
  },
  {
    id: 6,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Companion Character',
    viewsCount: 0,
    image: '/img/comics/page/6.webp',
    thumbnail: '/img/comics/thumbnail/6.webp',
  },
];

export const ITEMS: Item[] = [
  {
    id: 1,
    title: 'Cape',
    multiplier: 2,
    wearableName: '',
    balance: 0,
    image: '/img/items/full/1.gif',
    thumbnail: '/img/items/thumbnail/1.webp',
    empty: '/img/items/empty/1.svg',
  },
  {
    id: 2,
    title: 'Halo',
    multiplier: 1,
    wearableName: '',
    balance: 0,
    image: '/img/items/full/2.gif',
    thumbnail: '/img/items/thumbnail/2.webp',
    empty: '/img/items/empty/2.svg',
    equipped: true,
  },
  {
    id: 3,
    title: 'Diamond Bat',
    multiplier: 1,
    wearableName: '',
    balance: 0,
    image: '/img/items/full/3.gif',
    thumbnail: '/img/items/thumbnail/3.webp',
    empty: '/img/items/empty/3.svg',
  },
  {
    id: 4,
    title: 'Bread Bat',
    multiplier: 1,
    wearableName: '',
    balance: 0,
    image: '/img/items/full/4.gif',
    thumbnail: '/img/items/thumbnail/4.webp',
    empty: '/img/items/empty/4.svg',
  },
  {
    id: 5,
    title: 'Purple Bat',
    multiplier: 1,
    wearableName: '',
    balance: 0,
    image: '/img/items/full/5.gif',
    thumbnail: '/img/items/thumbnail/5.webp',
    empty: '/img/items/empty/5.svg',
  },
  {
    id: 6,
    title: 'Companion',
    multiplier: 3,
    wearableName: '',
    balance: 0,
    image: '/img/items/full/6.gif',
    thumbnail: '/img/items/thumbnail/6.webp',
    empty: '/img/items/empty/6.svg',
  },
  {
    id: 7,
    title: 'Citadel Key',
    multiplier: 0,
    wearableName: '',
    balance: 0,
    image: '/img/items/7.gif',
    thumbnail: '/img/items/thumbnail/7.webp',
    empty: '/img/items/empty/7.svg',
    isNew: false,
  },
];
