import type { Comic, Item } from '@/types/comic';

export const COMICS: Comic[] = [
  {
    id: 1,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Cape',
    viewsCount: 0,
    image: '/images/comics/page1.png',
    thumbnail: '/images/comics/thumbnail/page1.png',
  },
  {
    id: 2,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Halo',
    viewsCount: 0,
    image: '/images/comics/page2.png',
    thumbnail: '/images/comics/thumbnail/page2.png',
  },
  {
    id: 3,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Diamond Bat',
    viewsCount: 0,
    image: '/images/comics/page3.png',
    thumbnail: '/images/comics/thumbnail/page3.png',
  },
  {
    id: 4,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Bread Bat',
    viewsCount: 0,
    image: '/images/comics/page4.png',
    thumbnail: '/images/comics/thumbnail/page4.png',
  },
  {
    id: 5,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Purple Bat',
    viewsCount: 0,
    image: '/images/comics/page5.png',
    thumbnail: '/images/comics/thumbnail/page5.png',
  },
  {
    id: 6,
    title: 'Comic',
    multiplier: 1.5,
    wearableName: 'Companion Character',
    viewsCount: 0,
    image: '/images/comics/page6.png',
    thumbnail: '/images/comics/thumbnail/page6.png',
  },
];

export const ITEMS: Item[] = [
  {
    id: 1,
    title: 'Cape',
    multiplier: 2,
    wearableName: '',
    balance: 0,
    image: '/images/comics/items/1.gif',
    thumbnail: '/images/comics/items/thumbnail/1.png',
    empty: '/images/comics/items/empty/1.svg',
  },
  {
    id: 2,
    title: 'Halo',
    multiplier: 1,
    wearableName: '',
    balance: 0,
    image: '/images/comics/items/2.gif',
    thumbnail: '/images/comics/items/thumbnail/2.png',
    empty: '/images/comics/items/empty/2.svg',
    equipped: true,
  },
  {
    id: 3,
    title: 'Diamond Bat',
    multiplier: 1,
    wearableName: '',
    balance: 0,
    image: '/images/comics/items/3.gif',
    thumbnail: '/images/comics/items/thumbnail/3.png',
    empty: '/images/comics/items/empty/3.svg',
  },
  {
    id: 4,
    title: 'Bread Bat',
    multiplier: 1,
    wearableName: '',
    balance: 0,
    image: '/images/comics/items/4.gif',
    thumbnail: '/images/comics/items/thumbnail/4.png',
    empty: '/images/comics/items/empty/4.svg',
  },
  {
    id: 5,
    title: 'Purple Bat',
    multiplier: 1,
    wearableName: '',
    balance: 0,
    image: '/images/comics/items/5.gif',
    thumbnail: '/images/comics/items/thumbnail/5.png',
    empty: '/images/comics/items/empty/5.svg',
  },
  {
    id: 6,
    title: 'Companion',
    multiplier: 3,
    wearableName: '',
    balance: 0,
    image: '/images/comics/items/6.gif',
    thumbnail: '/images/comics/items/thumbnail/6.png',
    empty: '/images/comics/items/empty/6.svg',
  },
  {
    id: 7,
    title: 'Citadel Key',
    multiplier: 0,
    wearableName: '',
    balance: 0,
    image: '/images/comics/items/7.gif',
    thumbnail: '/images/comics/items/thumbnail/7.png',
    empty: '/images/comics/items/empty/7.svg',
    isNew: false,
  },
];
