export const HYDRAS = {
  '9901': {
    rarity: 'Meta',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Gold Chain Mail' },
      { trait_type: 'Bottom', value: 'Red Fustanella' },
      { trait_type: 'Footwear', value: 'Yellow Basic Shoes' },
      { trait_type: 'Hat', value: 'Gold Hoplite Corinthian' },
      { trait_type: 'Wrist', value: 'White/Red Sweatband' },
      { trait_type: 'Left Item', value: 'Gold Aspis Shield' },
      { trait_type: 'Right Item', value: 'Gold Doru Spear' },
    ],
  },
  '9902': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Ripe Pumpkin' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Curly' },
      { trait_type: 'Top', value: 'White Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Black Elbowpatch Jacket' },
      { trait_type: 'Bottom', value: 'Gray Kneepatch Jeans' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Black Basic' },
      { trait_type: 'Eyewear', value: 'Black Shades' },
      { trait_type: 'Neckwear', value: 'Red Tie' },
      { trait_type: 'Left Item', value: 'Money Bag' },
      { trait_type: 'Right Item', value: 'Diamond' },
    ],
  },
  '9903': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Signal Pink' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Blacksmith Shirt' },
      { trait_type: 'Outerwear', value: 'Dark Gray Overalls' },
      { trait_type: 'Footwear', value: 'Brown work boots' },
      { trait_type: 'Hat', value: 'Bandana' },
      { trait_type: 'Left Item', value: "Blacksmith's Hammer" },
      { trait_type: 'Right Item', value: 'Anvil' },
    ],
  },
  '9904': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Yellow T-Shirt' },
      { trait_type: 'Outerwear', value: 'Hawaiian Shirt' },
      { trait_type: 'Bottom', value: 'White Boxers' },
      { trait_type: 'Eyewear', value: 'Black Shades' },
    ],
  },
  '9905': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Curly' },
      { trait_type: 'Top', value: 'White T-Shirt' },
      { trait_type: 'Outerwear', value: 'Black Puffer Jacket' },
      { trait_type: 'Bottom', value: 'Orange Baggy Pants' },
      { trait_type: 'Footwear', value: 'Beige Mummy Shoes' },
      { trait_type: 'Hat', value: 'White Backwards Hat' },
      { trait_type: 'Eyewear', value: 'Red Shades' },
      { trait_type: 'Piercing', value: 'Gold Nose Ring' },
      { trait_type: 'Wrist', value: 'Gold Watch' },
      { trait_type: 'Neckwear', value: 'Gold Medal Necklace' },
      { trait_type: 'Left Item', value: 'Boombox' },
    ],
  },
  '9906': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Blonde Simple' },
      { trait_type: 'Top', value: 'Orange Longsleeve' },
      { trait_type: 'Outerwear', value: 'Brown Overalls' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'Brown Work boots' },
      { trait_type: 'Left Item', value: "Goldsmith's Hammer" },
      { trait_type: 'Right Item', value: 'Anvil' },
    ],
  },
  '9907': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Fade' },
      { trait_type: 'Beard', value: 'Huge Beard' },
      { trait_type: 'Top', value: 'Red T-Shirt' },
      { trait_type: 'Bottom', value: 'Denim Jeans' },
      { trait_type: 'Footwear', value: 'Red Basic Shoes' },
      { trait_type: 'Eyewear', value: 'Black Shades' },
      { trait_type: 'Wrist', value: 'Black Sweatband' },
    ],
  },
  '9908': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'White Targaryen' },
      { trait_type: 'Outerwear', value: 'Dress' },
      { trait_type: 'Footwear', value: 'Yellow Basic Shoes' },
    ],
  },
  '9909': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Orange T-Shirt' },
      { trait_type: 'Outerwear', value: 'Green Hoodie' },
      { trait_type: 'Bottom', value: 'Green Fustanella' },
      { trait_type: 'Footwear', value: 'Brown work boots' },
      { trait_type: 'Left Item', value: 'Knife' },
      { trait_type: 'Right Item', value: 'Toxotai Bow' },
    ],
  },
  '9910': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Black Curly' },
      { trait_type: 'Beard', value: 'Handlebar' },
      { trait_type: 'Outerwear', value: 'Poncho' },
      { trait_type: 'Hat', value: 'Sombrero' },
      { trait_type: 'Left Item', value: 'Snake' },
      { trait_type: 'Right Item', value: 'Vihuela Guitar' },
    ],
  },
  '9911': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Signal Pink' },
      { trait_type: 'Eye Color', value: 'Sparky Blue' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Brown Jumper' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'Beige Mummy Shoes' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Left Item', value: 'Bottle' },
      { trait_type: 'Right Item', value: 'Wine Glass' },
    ],
  },
  '9912': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Ornery Tangerine' },
      { trait_type: 'Eye Color', value: 'Primrose Path' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Quiff' },
      { trait_type: 'Top', value: 'Orange Longsleeve' },
      { trait_type: 'Outerwear', value: 'Brown Waistcoat' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Left Item', value: 'Carrot' },
      { trait_type: 'Right Item', value: 'Carrot' },
    ],
  },
  '9913': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White T-Shirt' },
      { trait_type: 'Bottom', value: 'White Boxers' },
      { trait_type: 'Footwear', value: 'White Basic Shoes' },
      { trait_type: 'Hat', value: 'White Tennis Cap' },
      { trait_type: 'Wrist', value: 'White Sweatband' },
      { trait_type: 'Neckwear', value: 'Gold Whistle' },
      { trait_type: 'Right Item', value: 'Tennis Racket' },
    ],
  },
  '9914': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Black T-Shirt' },
      { trait_type: 'Bottom', value: 'Green Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Eyewear', value: '3D Glasses' },
      { trait_type: 'Left Item', value: 'Popcorn' },
      { trait_type: 'Right Item', value: 'Soda' },
    ],
  },
  '9915': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Shadowclan' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'Primrose Path' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Shadowclan Robe' },
      { trait_type: 'Hat', value: 'Medium Buck Horns' },
      { trait_type: 'Right Item', value: 'Enchanted Wooden Dagger' },
    ],
  },
  '9916': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Red Spiky' },
      { trait_type: 'Top', value: 'White Torn Vest' },
      { trait_type: 'Bottom', value: 'Denim Jeans' },
      { trait_type: 'Footwear', value: 'Red Basic Shoes' },
      { trait_type: 'Wrist', value: 'Black Sweatband' },
      { trait_type: 'Right Item', value: 'Drumsticks' },
    ],
  },
  '9917': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Allegiance' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Dark Blue Dress Coat' },
      { trait_type: 'Bottom', value: 'Black Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Black Basic' },
      { trait_type: 'Hat', value: 'Top Hat' },
      { trait_type: 'Neckwear', value: 'Black Tie' },
      { trait_type: 'Right Item', value: 'Cane' },
    ],
  },
  '9918': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: "Police Officer's Shirt" },
      { trait_type: 'Bottom', value: 'Denim Jeans' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Black Basic' },
      { trait_type: 'Hat', value: 'Blue Police Hat' },
      { trait_type: 'Eyewear', value: 'Black Shades' },
      { trait_type: 'Left Item', value: 'Police Baton' },
      { trait_type: 'Right Item', value: 'Handcuffs' },
    ],
  },
  '9919': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Beard', value: 'White Long Beard' },
      { trait_type: 'Top', value: 'White T-Shirt' },
      { trait_type: 'Outerwear', value: 'Dark Blue Cowl' },
      { trait_type: 'Left Item', value: 'Wooden Spoon' },
      { trait_type: 'Right Item', value: 'Cauldron' },
    ],
  },
  '9920': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Black Pulled-Back' },
      { trait_type: 'Top', value: 'White Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Denim Overalls' },
      { trait_type: 'Left Item', value: 'Bottle' },
      { trait_type: 'Right Item', value: 'Bottle' },
    ],
  },
  '9921': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Allegiance' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White T-Shirt' },
      { trait_type: 'Print', value: 'Brown Skull' },
      { trait_type: 'Bottom', value: 'Green Jeans' },
      { trait_type: 'Footwear', value: 'Beige Mummy Shoes' },
      { trait_type: 'Hat', value: 'Green Beanie' },
      { trait_type: 'Left Item', value: 'Red/Yellow Skateboard' },
    ],
  },
  '9922': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Orange Robe' },
      { trait_type: 'Left Item', value: 'Buddhism Book' },
    ],
  },
  '9923': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Quiff' },
      { trait_type: 'Top', value: 'Green/White Gingham Button-Up' },
      { trait_type: 'Bottom', value: 'Beige Mummy Pants' },
      { trait_type: 'Neckwear', value: 'Red Tie' },
      { trait_type: 'Left Item', value: 'Wood Plane' },
      { trait_type: 'Right Item', value: 'Ruler' },
    ],
  },
  '9924': {
    rarity: 'Legendary',
    attributes: [
      { trait_type: 'Hydra', value: 'Commander' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Legendary Bronze Cuirass' },
      { trait_type: 'Bottom', value: 'Legendary Bronze Greaves' },
      { trait_type: 'Footwear', value: 'Legendary Bronze Sabatons' },
      { trait_type: 'Hat', value: 'Legendary Bronze Corinthian' },
      { trait_type: 'Hands', value: 'Legendary Bronze Gauntlets' },
      { trait_type: 'Left Item', value: 'Legendary Bronze Shield' },
      { trait_type: 'Right Item', value: 'Legendary Bronze Trident' },
    ],
  },
  '9925': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Tan Collared T-Shirt' },
      { trait_type: 'Outerwear', value: 'Brown Overalls' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Hat', value: 'Red Construction Helmet' },
      { trait_type: 'Hands', value: 'Brown Gloves' },
      { trait_type: 'Left Item', value: 'Construction Hammer' },
      { trait_type: 'Right Item', value: 'Chisel' },
    ],
  },
  '9926': {
    rarity: 'Meta',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Signal Pink' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'Primrose Path' },
      { trait_type: 'Hair', value: 'White Curly' },
      { trait_type: 'Top', value: 'White Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'White Dress Coat' },
      { trait_type: 'Bottom', value: 'Gray Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Hat', value: 'White Top Hat' },
      { trait_type: 'Eyewear', value: 'Monocle' },
      { trait_type: 'Neckwear', value: 'Yellow Bowtie' },
    ],
  },
  '9927': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White Longline T-Shirt' },
      { trait_type: 'Outerwear', value: 'Brown Trenchcoat' },
      { trait_type: 'Bottom', value: 'Denim Jeans' },
      { trait_type: 'Footwear', value: 'Brown Mummy Shoes' },
      { trait_type: 'Belt', value: 'White Studded' },
      { trait_type: 'Hat', value: 'Dark Gray Beanie' },
      { trait_type: 'Piercing', value: 'White Stud' },
      { trait_type: 'Neckwear', value: 'Thick Red Scarf' },
    ],
  },
  '9928': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Gold Cuirass' },
      { trait_type: 'Bottom', value: 'Gold Greaves' },
      { trait_type: 'Footwear', value: 'Gold Sabatons' },
      { trait_type: 'Hat', value: 'Gold Peltast Corinthian' },
      { trait_type: 'Hands', value: 'Gold Gauntlets' },
      { trait_type: 'Left Item', value: 'Gold Pelte Shield' },
      { trait_type: 'Right Item', value: 'Gold Javelin' },
    ],
  },
  '9929': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Tan Toga' },
      { trait_type: 'Back', value: 'Wings' },
      { trait_type: 'Footwear', value: 'Yelllow Basic Shoes' },
      { trait_type: 'Hat', value: 'Gold Ornis Corinthian' },
      { trait_type: 'Wrist', value: 'Brown Wristband' },
      { trait_type: 'Left Item', value: 'Ornis Javelin' },
    ],
  },
  '9930': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Single Orgin' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Space Suit' },
      { trait_type: 'Back', value: 'Space Pack' },
      { trait_type: 'Bottom', value: 'Space Pants' },
      { trait_type: 'Footwear', value: 'Space Boots' },
      { trait_type: 'Hat', value: 'Space Helmet' },
    ],
  },
  '9931': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Signal Pink' },
      { trait_type: 'Eye Color', value: 'Sparky Blue' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White Longline T-Shirt' },
      { trait_type: 'Outerwear', value: 'Dark Blue Collared Overshirt' },
      { trait_type: 'Bottom', value: 'Gray Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Hat', value: 'Red Headband' },
    ],
  },
  '9932': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Blue/White Striped Longline  T-Shirt' },
      { trait_type: 'Bottom', value: 'Blue Shorts' },
      { trait_type: 'Footwear', value: 'Black Loafers' },
      { trait_type: 'Hat', value: 'Red Beanie' },
      { trait_type: 'Left Item', value: 'Spyglass' },
      { trait_type: 'Right Item', value: 'Helm' },
    ],
  },
  '9933': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Mummy Wrap' },
      { trait_type: 'Bottom', value: 'Mummy Wrap' },
      { trait_type: 'Hat', value: 'Mummy Wrap' },
      { trait_type: 'Left Item', value: 'Arm Sling' },
    ],
  },
  '9934': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Royalty' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'White Toga' },
      { trait_type: 'Hat', value: 'Hydra Princess Crown' },
      { trait_type: 'Right Item', value: 'Gold Trident' },
    ],
  },
  '9935': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Black T-Shirt' },
      { trait_type: 'Outerwear', value: 'Construction Vest' },
      { trait_type: 'Bottom', value: 'Denim Jeans' },
      { trait_type: 'Hat', value: 'Yellow Construction Helmet' },
      { trait_type: 'Right Item', value: 'Pick Axe' },
    ],
  },
  '9936': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Naked' },
      { trait_type: 'Skin Color', value: 'Signal Pink' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
    ],
  },
  '9937': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Allegiance' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Curly' },
      { trait_type: 'Top', value: 'White T-Shirt' },
      { trait_type: 'Print', value: 'Brown Skull' },
      { trait_type: 'Bottom', value: 'Green Jeans' },
      { trait_type: 'Footwear', value: 'Beige Mummy Shoes' },
      { trait_type: 'Hat', value: 'White Backwards Hat' },
      { trait_type: 'Left Item', value: 'Red/Yellow Skateboard' },
    ],
  },
  '9938': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Blue Side Part' },
      { trait_type: 'Top', value: 'Yellow/White Striped Longline T-Shirt' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'White Basic Shoes' },
      { trait_type: 'Eyewear', value: 'Black Shades' },
      { trait_type: 'Piercing', value: 'White Diamond Stud' },
    ],
  },
  '9939': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hat', value: 'Brown Demon Horns' },
      { trait_type: 'Right Item', value: 'Red Demon Trident' },
    ],
  },
  '9940': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Naked' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'Japanese Carmine' },
    ],
  },
  '9941': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Green Spiky' },
      { trait_type: 'Top', value: 'Dark Gray T-Shirt' },
      { trait_type: 'Outerwear', value: 'Black Leather Waistcoat' },
      { trait_type: 'Print', value: 'White Skull' },
      { trait_type: 'Bottom', value: 'Black Torn Jeans' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Black Studded' },
      { trait_type: 'Piercing', value: 'Gold Nose Ring' },
      { trait_type: 'Wrist', value: 'Black Studded Cuff' },
    ],
  },
  '9942': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Blonde Flow' },
      { trait_type: 'Outerwear', value: 'Silver Chain Mail' },
      { trait_type: 'Bottom', value: 'Gray Pants' },
      { trait_type: 'Eyewear', value: 'Brown Eye Pad' },
      { trait_type: 'Hands', value: 'Brown Leather Gloves' },
      { trait_type: 'Left Item', value: 'Knife' },
      { trait_type: 'Right Item', value: 'Toxotai Bow' },
    ],
  },
  '9943': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Greenery' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Cuirass' },
      { trait_type: 'Bottom', value: 'Bronze Greaves' },
      { trait_type: 'Footwear', value: 'Brown Mummy Shoes' },
      { trait_type: 'Hat', value: 'Bronze Peltast Corinthian' },
      { trait_type: 'Hands', value: 'Bronze Gauntlets' },
      { trait_type: 'Left Item', value: 'Bronze Pelte Shield' },
      { trait_type: 'Right Item', value: 'Javelin' },
    ],
  },
  '9944': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Blonde Curly' },
      { trait_type: 'Top', value: 'Longline Tie Dye T-Shirt' },
      { trait_type: 'Bottom', value: 'White Boxers' },
      { trait_type: 'Hat', value: 'Red/Pink Striped Bandana' },
      { trait_type: 'Eyewear', value: 'Glasses' },
    ],
  },
  '9945': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Shadowclan' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Shadowclan Robe' },
      { trait_type: 'Hat', value: 'Small Fawn Horns' },
      { trait_type: 'Right Item', value: 'Enchanted Ice Dagger' },
    ],
  },
  '9946': {
    rarity: 'Meta',
    attributes: [
      { trait_type: 'Hydra', value: 'Royalty' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Dark Blue Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Gold Epaulettes' },
      { trait_type: 'Back', value: "Prince's Robe" },
      { trait_type: 'Bottom', value: 'White Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Golden Studded' },
      { trait_type: 'Hat', value: "Prince's Crown" },
      { trait_type: 'Neckwear', value: "Prince's Amulet" },
      { trait_type: 'Right Item', value: 'Golden Trident' },
    ],
  },
  '9947': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Begonia' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Flow' },
      { trait_type: 'Top', value: 'Brown Poet Shirt' },
      { trait_type: 'Back', value: 'Brown Cape' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'Brown High-Top Boots' },
      { trait_type: 'Left Item', value: 'Lute' },
    ],
  },
  '9948': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Red/Black Gingham Button-Up' },
      { value: 'Laptop Bag' },
      { trait_type: 'Bottom', value: 'Dark Blue Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Hat', value: 'Dark Gray Beanie' },
      { trait_type: 'Eyewear', value: 'Glasses' },
      { trait_type: 'Right Item', value: 'Cardboard Coffee Cup' },
    ],
  },
  '9949': {
    rarity: 'Meta',
    attributes: [
      { trait_type: 'Hydra', value: 'Shadowclan' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'Cherry Soda' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Shadowclan Robe' },
      { trait_type: 'Hat', value: 'Long Antelope Horns' },
      { trait_type: 'Right Item', value: 'Enchanted Fire Dagger' },
    ],
  },
  '9950': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Bottom', value: 'Beige Frayed Jorts' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Left Item', value: 'Grapes' },
      { trait_type: 'Right Item', value: 'Sickel' },
    ],
  },
  '9951': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Green Longsleeve' },
      { trait_type: 'Print', value: '420' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'White Basic Shoes' },
      { trait_type: 'Hat', value: 'Safari Hat' },
    ],
  },
  '9952': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Signal Pink' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Silver Cuirass' },
      { trait_type: 'Bottom', value: 'Silver Tassets' },
      { trait_type: 'Footwear', value: 'Silver Sabatons' },
      { trait_type: 'Hat', value: 'Silver Hoplite Corinthian' },
      { trait_type: 'Hands', value: 'Silver Gauntlets' },
      { trait_type: 'Left Item', value: 'Silver Aspis Shield' },
      { trait_type: 'Right Item', value: 'Doru Spear' },
    ],
  },
  '9953': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Dark Gray Curly' },
      { trait_type: 'Top', value: 'Dark Brown Longsleeve Shirt' },
      { trait_type: 'Outerwear', value: 'Leather Cuirass' },
      { trait_type: 'Bottom', value: 'Dark Brown Pants' },
      { trait_type: 'Footwear', value: 'Brown Basic Shoes' },
      { trait_type: 'Hat', value: 'Yellow Bycocket Hat' },
      { trait_type: 'Wrist', value: 'Brown Leather Cuffs' },
      { trait_type: 'Hands', value: 'Brown Leather Gloves' },
      { trait_type: 'Left Item', value: 'Arrow' },
      { trait_type: 'Right Item', value: 'Toxotai Bow' },
    ],
  },
  '9954': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'White Toga' },
      { trait_type: 'Belt', value: 'Brown Leather' },
      { trait_type: 'Hat', value: 'Small Fawn Horns' },
      { trait_type: 'Wrist', value: 'Gold Bracelet' },
      { trait_type: 'Left Item', value: 'Flute' },
    ],
  },
  '9955': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Black Messy' },
      { trait_type: 'Beard', value: 'Black Scraggly Beard' },
      { trait_type: 'Top', value: 'Tan Torn Vest' },
      { trait_type: 'Bottom', value: 'Dark Gray Torn Shorts' },
      { trait_type: 'Right Item', value: 'Mug-O-Coins' },
    ],
  },
  '9956': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Signal Pink' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Blonde Mohawk' },
      { trait_type: 'Outerwear', value: 'Space Marine Armor' },
      { trait_type: 'Bottom', value: 'Dark Blue Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Left Item', value: 'Space Gun' },
    ],
  },
  '9957': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White T-Shirt' },
      { trait_type: 'Outerwear', value: 'Brown Open Jacket' },
      { trait_type: 'Bottom', value: 'Beige kneepatch jeans' },
      { trait_type: 'Left Item', value: 'Poop' },
      { trait_type: 'Right Item', value: 'Poop' },
    ],
  },
  '9958': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Pulled-Back' },
      { trait_type: 'Top', value: 'Tan Collared Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Brown Suspenders' },
      { trait_type: 'Bottom', value: 'Dark Blue Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
    ],
  },
  '9959': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Signal Pink' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Diamond Special Forces Cuirass' },
      { trait_type: 'Back', value: 'Red Cape' },
      { trait_type: 'Bottom', value: 'Diamond Greaves' },
      { trait_type: 'Footwear', value: 'Diamond Sabatons' },
      { trait_type: 'Hat', value: 'Diamond Special Forces Corinthian' },
      { trait_type: 'Hands', value: 'Diamond Gauntlets' },
      { trait_type: 'Right Item', value: 'Diamond Special Forces Trident' },
    ],
  },
  '9960': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Blue T-Shirt' },
      { trait_type: 'Outerwear', value: 'Dark Gray Longline Longsleeve Open Button-Up' },
      { trait_type: 'Bottom', value: 'Dark Blue Track Pants' },
      { trait_type: 'Hat', value: 'Dark Gray Beanie' },
      { trait_type: 'Left Item', value: 'Scooter' },
    ],
  },
  '9961': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Pulled-Back' },
      { trait_type: 'Top', value: 'White Collared Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Brown Open Jacket' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Eyewear', value: 'Black Eyes' },
      { trait_type: 'Right Item', value: 'Dice' },
    ],
  },
  '9962': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Quiff' },
      { trait_type: 'Outerwear', value: 'Puff Sleeve Top' },
      { trait_type: 'Bottom', value: 'Dark Blue Pants' },
      { trait_type: 'Footwear', value: 'Brown Work Boots' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Neckwear', value: 'White Puff' },
      { trait_type: 'Right Item', value: 'Skull' },
    ],
  },
  '9963': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Pulled-Back' },
      { trait_type: 'Top', value: 'White Collared Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Dark Blue Closed Dinner Jacket' },
      { trait_type: 'Bottom', value: 'Dark Blue Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Neckwear', value: 'Red Tie' },
    ],
  },
  '9964': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Black Hooded Robe' },
      { trait_type: 'Right Item', value: 'Golden Seed Piece' },
    ],
  },
  '9965': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Ripe Pumpkin' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Silver Special Forces Cuirass' },
      { trait_type: 'Back', value: 'Red Cape' },
      { trait_type: 'Bottom', value: 'Silver Greaves' },
      { trait_type: 'Footwear', value: 'Silver Sabatons' },
      { trait_type: 'Belt', value: 'Brown Torn Utility Belt' },
      { trait_type: 'Hat', value: 'Silver Special Forces Corinthian' },
      { trait_type: 'Hands', value: 'Silver Gauntlets' },
      { trait_type: 'Right Item', value: 'Fire Special Forces Trident' },
    ],
  },
  '9966': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Ripe Pumpkin' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Simple' },
      { trait_type: 'Top', value: 'Tan Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Brown Waistcoat' },
      { trait_type: 'Bottom', value: 'Beige Pants' },
      { trait_type: 'Footwear', value: 'Red Basic Shoes' },
      { trait_type: 'Hat', value: 'Red Feathered Beret' },
      { trait_type: 'Wrist', value: 'Brown Cuffs' },
      { trait_type: 'Left Item', value: 'Artist Paintbrush' },
      { trait_type: 'Right Item', value: 'Artist Palette' },
    ],
  },
  '9967': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Black Flow' },
      { value: 'Black T-Shirt' },
      { trait_type: 'Bottom', value: 'Black Jeans' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Wrist', value: 'Black/White Sweatband' },
      { trait_type: 'Left Item', value: 'Flying V Electric Guitar' },
    ],
  },
  '9968': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'White Horseshoe' },
      { trait_type: 'Beard', value: 'White Long Beard' },
      { trait_type: 'Outerwear', value: 'Tan Toga' },
      { value: 'Brown Sandals' },
      { trait_type: 'Left Item', value: 'Book on Philosophy' },
    ],
  },
  '9969': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Naked' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
    ],
  },
  '9970': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Ripe Pumpkin' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Green T-Shirt' },
      { trait_type: 'Bottom', value: 'Dark Blue Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Left Item', value: 'Diamond' },
      { trait_type: 'Right Item', value: 'Diamond' },
    ],
  },
  '9971': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Greenery' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Tan Torn T-Shirt' },
      { trait_type: 'Back', value: 'Arrows' },
      { trait_type: 'Bottom', value: 'Torn Dark Green Pants' },
      { trait_type: 'Footwear', value: 'Brown Mummy Shoes' },
      { value: 'Dark Green' },
      { trait_type: 'Hands', value: 'Pink Gloves' },
      { trait_type: 'Neckwear', value: 'Red Scarf' },
      { trait_type: 'Left Item', value: 'Knife' },
      { trait_type: 'Right Item', value: 'Toxotai Bow' },
    ],
  },
  '9972': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Naked' },
      { trait_type: 'Skin Color', value: 'Greenery' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
    ],
  },
  '9973': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White T-Shirt' },
      { trait_type: 'Outerwear', value: 'Dark Brown Waistcoat' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Left Item', value: 'Bowl of Olives' },
    ],
  },
  '9974': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'NL T-Shirt' },
      { trait_type: 'Print', value: 'Nifty' },
      { trait_type: 'Bottom', value: 'NL Pants' },
      { trait_type: 'Footwear', value: 'White Basic Shoes' },
      { trait_type: 'Hat', value: 'Nifty Cap' },
      { trait_type: 'Eyewear', value: 'Black Shades' },
      { trait_type: 'Left Item', value: 'NL Cellphone' },
      { trait_type: 'Right Item', value: 'Nifty Mug' },
    ],
  },
  '9975': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'Primrose Path' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'White Toga' },
      { trait_type: 'Left Item', value: 'Hanging Bass Drum' },
    ],
  },
  '9976': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Greenery' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Green Cuirass' },
      { trait_type: 'Back', value: 'Wings' },
      { trait_type: 'Bottom', value: 'Green Metal Underpants' },
      { trait_type: 'Footwear', value: 'Brown Mummy Shoes' },
      { trait_type: 'Hat', value: 'Bronze Ornis Corinthian' },
      { trait_type: 'Wrist', value: 'Brown Wristband' },
      { trait_type: 'Left Item', value: 'Ornis Javelin' },
    ],
  },
  '9977': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Naked' },
      { trait_type: 'Skin Color', value: 'White' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
    ],
  },
  '9978': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Gray Quiff' },
      { trait_type: 'Top', value: 'Red T-Shirt' },
      { trait_type: 'Outerwear', value: 'Tan Toga' },
      { trait_type: 'Footwear', value: 'Red Basic Shoes' },
      { trait_type: 'Eyewear', value: 'Glasses' },
      { trait_type: 'Left Item', value: 'Square Ruler' },
      { trait_type: 'Right Item', value: 'Blueprints' },
    ],
  },
  '9979': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Naked' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
    ],
  },
  '9980': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Apron' },
      { trait_type: 'Hat', value: "Baker's Hat" },
      { trait_type: 'Left Item', value: "Baker's Tray" },
    ],
  },
  '9981': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Silver Cuirass' },
      { trait_type: 'Bottom', value: 'Silver Greaves' },
      { trait_type: 'Footwear', value: 'Silver Sabatons' },
      { trait_type: 'Hat', value: 'Silver Peltast Corinthian' },
      { trait_type: 'Hands', value: 'Silver Gauntlets' },
      { trait_type: 'Left Item', value: 'Silver Pelte Shield' },
      { trait_type: 'Right Item', value: 'Silver Javelin' },
    ],
  },
  '9982': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Brown T-Shirt' },
      { trait_type: 'Outerwear', value: 'Smock' },
      { trait_type: 'Hat', value: 'Laurel Wreath' },
      { trait_type: 'Left Item', value: 'Harp' },
    ],
  },
  '9983': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Brown Toga' },
      { trait_type: 'Footwear', value: 'Brown Mummy Shoes' },
      { trait_type: 'Hat', value: 'Farmer Hat' },
      { trait_type: 'Left Item', value: 'Wheat' },
      { trait_type: 'Right Item', value: 'Sickle' },
    ],
  },
  '9984': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Bronze Cuirass' },
      { trait_type: 'Bottom', value: 'Bronze Tassets' },
      { trait_type: 'Footwear', value: 'Bronze Sabatons' },
      { trait_type: 'Hat', value: 'Bronze Hoplite Corinthian' },
      { trait_type: 'Hands', value: 'Bronze Gauntlets' },
      { trait_type: 'Left Item', value: 'Bronze Aspis Shield' },
      { trait_type: 'Right Item', value: 'Doru Spear' },
    ],
  },
  '9985': {
    rarity: 'Rare',
    attributes: [
      { trait_type: 'Hydra', value: 'Royalty' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Gray Curly' },
      { trait_type: 'Top', value: 'Jester Top' },
      { trait_type: 'Bottom', value: 'Jester Pants' },
      { trait_type: 'Footwear', value: 'Purple Boots' },
      { trait_type: 'Belt', value: 'Jester Belt' },
      { trait_type: 'Hat', value: 'Jester Hat' },
      { trait_type: 'Eyewear', value: 'Jester Mask' },
      { trait_type: 'Hands', value: 'Black Gloves' },
    ],
  },
  '9986': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Green Cut-off T-Shirt' },
      { trait_type: 'Outerwear', value: 'White Toga' },
      { trait_type: 'Belt', value: 'Brown Tool Belt' },
      { trait_type: 'Hat', value: 'Red Construction Helmet' },
      { trait_type: 'Left Item', value: "Carpenter's Hammer" },
      { trait_type: 'Right Item', value: 'Blueprints' },
    ],
  },
  '9987': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Icy Brook' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Gray Quiff' },
      { trait_type: 'Top', value: 'White Longsleeve Collared' },
      { trait_type: 'Outerwear', value: 'Brown Suit Vest' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Eyewear', value: 'Glasses' },
      { trait_type: 'Neckwear', value: 'Red Tie' },
    ],
  },
  '9988': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Camo Closed Jacket' },
      { trait_type: 'Bottom', value: 'Camo Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Hat', value: 'Camo Hat' },
      { trait_type: 'Eyewear', value: 'Black Shades' },
    ],
  },
  '9989': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Brown Curly' },
      { trait_type: 'Top', value: 'Black T-shirt' },
      { trait_type: 'Bottom', value: 'Gray Jorts' },
      { trait_type: 'Footwear', value: 'Gray/Black Running Shoes' },
      { trait_type: 'Belt', value: 'Black Basic' },
      { trait_type: 'Hat', value: 'Red Beanie' },
      { trait_type: 'Left Item', value: 'Vanilla Ice Cream' },
      { trait_type: 'Right Item', value: 'Red Balloon' },
    ],
  },
  '9990': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Tan Toga' },
      { trait_type: 'Back', value: 'Wings' },
      { trait_type: 'Footwear', value: 'Beige Mummy Shoes' },
      { trait_type: 'Hat', value: 'Gold Ornis Corinthian' },
      { trait_type: 'Wrist', value: 'Tan Sweatband' },
      { trait_type: 'Left Item', value: 'Ornis Javelin' },
    ],
  },
  '9991': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'White' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Hair', value: 'Blue Sidecut' },
      { trait_type: 'Top', value: 'Blue T-Shirt' },
      { trait_type: 'Outerwear', value: 'Gray Spiked Jacket' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Belt', value: 'Black Basic' },
      { trait_type: 'Eyewear', value: 'Red Scouter' },
    ],
  },
  '9992': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White T-Shirt' },
      { trait_type: 'Outerwear', value: 'Green Sweater Vest' },
      { trait_type: 'Bottom', value: 'Blue Pants' },
      { trait_type: 'Footwear', value: 'Brown Mummy Shoes' },
      { trait_type: 'Hat', value: 'Brown Fisherman Hat' },
      { trait_type: 'Left Item', value: 'Fish' },
      { trait_type: 'Right Item', value: 'Fishing Pole' },
    ],
  },
  '9993': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Tan Striped T-shirt' },
      { trait_type: 'Outerwear', value: 'Brown Overcoat' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'Brown Mummy Shoes' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Hat', value: 'Tan Deerstalker Hat' },
      { trait_type: 'Left Item', value: 'Magnifying Glass' },
    ],
  },
  '9994': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Traditionalist' },
      { trait_type: 'Skin Color', value: 'Pimrose Path' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Black T-shirt' },
      { trait_type: 'Outerwear', value: 'Gray V-cut Longsleeve' },
      { trait_type: 'Bottom', value: 'Black Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Eyewear', value: "Jeweler's Loupe" },
      { trait_type: 'Left Item', value: "Jeweler's Hammer" },
      { trait_type: 'Right Item', value: 'Jewel Cluster' },
    ],
  },
  '9995': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Battalion' },
      { trait_type: 'Skin Color', value: 'Greenery' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Outerwear', value: 'Gold Special Forces Cuirass' },
      { trait_type: 'Back', value: 'Red Elite Cape' },
      { trait_type: 'Bottom', value: 'Bronze Tassets' },
      { trait_type: 'Footwear', value: 'Gold Sabatons' },
      { trait_type: 'Hat', value: 'Gold Special Forces Corinthian' },
      { trait_type: 'Right Item', value: 'Silver Special Forces Trident' },
    ],
  },
  '9996': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Cherry Soda' },
      { trait_type: 'Eye Color', value: 'Primrose Path' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Tan Collared T-shirt' },
      { trait_type: 'Bottom', value: 'Ripped Blue Jeans' },
      { trait_type: 'Belt', value: 'Brown Basic' },
      { trait_type: 'Hat', value: 'Ranger Cap' },
      { trait_type: 'Right Item', value: 'Jewel Cluster' },
    ],
  },
  '9997': {
    rarity: 'Meta',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Atmosphere' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'Tropical Open Collared Button-Up Shirt' },
      { trait_type: 'Bottom', value: 'Green Swimsuit' },
      { trait_type: 'Footwear', value: 'White Basic Shoes' },
      { trait_type: 'Belt', value: 'White Studded' },
      { trait_type: 'Hat', value: 'Straw Sun Hat' },
      { trait_type: 'Eyewear', value: 'Black Shades' },
      { trait_type: 'Neckwear', value: 'Hawaiian Lei' },
      { trait_type: 'Right Item', value: 'Trident' },
    ],
  },
  '9998': {
    rarity: 'Common',
    attributes: [
      { trait_type: 'Hydra', value: 'Outlier' },
      { trait_type: 'Skin Color', value: 'Range Land' },
      { trait_type: 'Eye Color', value: 'White' },
      { trait_type: 'Pupil Color', value: 'River Styx' },
      { trait_type: 'Top', value: 'White Collared Longsleeve Button-Up' },
      { trait_type: 'Outerwear', value: 'Brown Dinner Jacket' },
      { trait_type: 'Bottom', value: 'Brown Pants' },
      { trait_type: 'Footwear', value: 'Black Basic Shoes' },
      { trait_type: 'Neckwear', value: 'Red Tie' },
      { trait_type: 'Left Item', value: 'Key' },
    ],
  },
  '9999': { rarity: 'Meta', attributes: [] },
  '10000': { rarity: 'Meta', attributes: [] },
};
