export const TRAIT_INDEXES: Record<number, string> = {
  0: 'tribe',
  1: 'skinColor',
  2: 'furColor',
  3: 'eyeColor',
  4: 'pupilColor',
  5: 'hair',
  6: 'mouth',
  7: 'beard',
  8: 'top',
  9: 'outerwear',
  10: 'print',
  11: 'bottom',
  12: 'footwear',
  13: 'belt',
  14: 'hat',
  15: 'eyewear',
  16: 'piercing',
  17: 'wrist',
  18: 'hands',
  19: 'neckwear',
  20: 'leftItem',
  21: 'rightItem',
  22: 'property',
}
