// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Twitter as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTwitter(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTwitter;
