// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Camera as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCamera(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCamera;
