// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Download as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconDownload(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconDownload;
