// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { CornerUpLeft as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCornerUpLeft(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCornerUpLeft;
