// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Slash as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconSlash(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconSlash;
