import type { FontFamily, Theme, ThemeOptions } from '../types';

const customTypography = (theme: Theme, borderRadius: number, fontFamily: FontFamily): ThemeOptions['typography'] => ({
  fontFamily: fontFamily.default.style.fontFamily,
  fontWeightLight: 200,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  fontSize: 16,
  h1: {
    color: 'var(--color-foreground)',
    fontFamily: 'var(--font-header)',
    fontSize: 'var(--text-4xl)' /* 2.25rem */,
    fontWeight: 'var(--font-weight-bold)',
    letterSpacing: 'var(--header-letter-spacing)',
    lineHeight: 'var(--text-4xl--line-height)',
  },
  h2: {
    color: 'var(--color-foreground)',
    fontFamily: 'var(--font-header)',
    fontSize: 'var(--text-3xl)' /* 1.875rem */,
    fontWeight: 'var(--font-weight-bold)',
    letterSpacing: 'var(--header-letter-spacing)',
    lineHeight: 'var(--text-3xl--line-height)',
  },
  h3: {
    color: 'var(--color-foreground)',
    fontFamily: 'var(--font-header)',
    fontSize: 'var(--text-2xl)' /* 1.5rem */,
    fontWeight: 'var(--font-weight-bold)',
    letterSpacing: 'var(--header-letter-spacing)',
    lineHeight: 'var(--text-2xl--line-height)',
  },
  h4: {
    color: 'var(--color-foreground)',
    fontFamily: 'var(--font-subheader)',
    fontSize: 'var(--text-xl)' /* 1.25rem */,
    fontWeight: 'var(--font-weight-normal)',
    letterSpacing: 'var(--subheader-letter-spacing)',
    lineHeight: 'var(--text-xl--line-height)',
  },
  h5: {
    color: 'var(--color-foreground)',
    fontFamily: 'var(--font-subheader)',
    fontSize: 'var(--text-lg)' /* 1.125rem */,
    fontWeight: 'var(--font-weight-normal)',
    letterSpacing: 'var(--subheader-letter-spacing)',
    lineHeight: 'var(--text-lg--line-height)',
  },
  h6: {
    color: 'var(--color-foreground)',
    fontFamily: 'var(--font-subheader)',
    fontSize: 'var(--text-base)' /* 1rem */,
    fontWeight: 'var(--font-weight-normal)',
    letterSpacing: 'var(--subheader-letter-spacing)',
    lineHeight: 'var(--text-base--line-height)',
  },
  subtitle1: { fontSize: 'var(--text-sm)' /* 0.875rem */, fontWeight: 500, color: 'var(--color-foreground)' },
  subtitle2: { fontSize: 'var(--text-xs)' /* 0.75rem */, fontWeight: 400, color: 'var(--color-muted-foreground)' },
  caption: { fontSize: 'var(--text-xs)' /* 0.75rem */, color: 'var(--color-muted-foreground)', fontWeight: 400 },
  body1: { fontSize: 'var(--text-base)' /* 1rem */, fontWeight: 400, lineHeight: '1.334em' },
  body2: {
    fontSize: 'var(--text-sm)' /* 0.875rem */,
    letterSpacing: '0em',
    fontWeight: 'var(--font-normal)',
    lineHeight: '1.5em',
    color: 'var(--color-foreground)',
  },
  button: { textTransform: 'capitalize', fontSize: 'var(--text-sm)' /* 0.875rem */ },
  customInput: {
    marginTop: 1,
    marginBottom: 1,
    '& > label': { top: 23, left: 0, color: 'var(--color-muted-foreground)', '&[data-shrink="false"]': { top: 5 } },
    '& > div > input': { padding: '30.5px 14px 11.5px !important' },
    '& legend': { display: 'none' },
    '& fieldset': { top: 0 },
  },
  mainContent: {
    backgroundColor: 'var(--color-background)',
    width: '100%',
    minHeight: 'calc(100vh - 100px)',
    flexGrow: 1,
    borderRadius: 'var(--border-radius-default)',
  },
  menuCaption: {
    fontSize: 'var(--text-sm)' /* 0.875rem */,
    fontWeight: 'var(--font-medium)',
    color: 'var(--color-muted-foreground)',
    padding: '6px',
    textTransform: 'capitalize',
    marginTop: '10px',
  },
  subMenuCaption: {
    fontSize: 'var(--text-xs)' /* 0.75rem */,
    fontWeight: 'var(--font-medium)',
    color: 'var(--color-muted-foreground)',
    textTransform: 'capitalize',
  },
  commonAvatar: { cursor: 'pointer', borderRadius: 'var(--border-radius-default)' },
  smallAvatar: { width: '22px', height: '22px', fontSize: 'var(--text-base)' /* 1rem */ },
  mediumAvatar: { width: '34px', height: '34px', fontSize: 'var(--text-xl)' /* 1.25rem */ },
  largeAvatar: { width: '44px', height: '44px', fontSize: 'var(--text-2xl)' /* 1.5rem */ },
});

export default customTypography;
