// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Battery as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconBattery(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconBattery;
