// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Heart as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconHeart(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconHeart;
