// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Meh as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMeh(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMeh;
