// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Gift as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconGift(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconGift;
