packages:
  - 'apps/*'
  - 'packages/*'

nodeVersion: 24.18.0
engineStrict: true
optimisticRepeatInstall: false
verifyDepsBeforeRun: error

publicHoistPattern:
  - '*import-in-the-middle*'
  - '*require-in-the-middle*'

overrides:
  'bnc-sdk>crypto-es': ^2.1.0
  'bnc-notify>uuid': 3.4.0
  'bn.js@>=4 <4.12.3': 4.12.3
  'brace-expansion@>=2 <2.0.3': 2.0.3
  'cookie@<0.7.0': 0.7.2
  'diff@>=5 <5.2.2': 5.2.2
  'esbuild@<0.28.1': 0.28.1
  'fast-uri@>=3 <3.1.2': 3.1.2
  'immutable@>=4 <4.3.8': 4.3.8
  'minimatch@>=5 <5.1.8': 5.1.8
  'minimatch@>=9 <9.0.7': 9.0.7
  'postcss@<8.5.10': 8.5.19
  protobufjs: 7.6.3
  'serialize-javascript@<7.0.5': 7.0.5
  'shell-quote@<=1.8.3': 1.8.4
  'tmp@<0.2.7': 0.2.7
  'undici@<6.27.0': 6.27.0
  'uuid@<11.1.1': 11.1.1
  'vite@>=7 <7.3.5': 7.3.5
  'websocket-driver@<0.7.5': 0.7.5
  'webpack@>=5 <5.104.1': 5.104.1
  'ws@>=7 <7.5.11': 7.5.11
  'ws@>=8 <8.21.0': 8.21.0
  zod: ^4.4.3

peerDependencyRules:
  allowedVersions:
    '@types/react-dom': 19.2.3
    '@types/react': 19.2.17
    cross-fetch: '4'
    crypto-es: ^2.1.0
    lit: 3.3.1
    next: 16.2.10
    react-dom: ^19.2.7
    react: ^19.2.7
    three: 0.181.2

allowBuilds:
  '@axelar-network/axelarjs-sdk': true
  '@opensea/seaport-js': true
  '@prisma/engines': true
  '@reown/appkit': true
  '@sentry/cli': true
  '@swc/core': true
  '@tailwindcss/oxide': true
  bufferutil: true
  core-js: true
  core-js-pure: true
  esbuild: true
  keccak: true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
