// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Tag as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTag(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTag;
