// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ToggleLeft as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconToggleLeft(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconToggleLeft;
