// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Wifi as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconWifi(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconWifi;
