// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { MinusSquare as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMinusSquare(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMinusSquare;
