// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { BellOff as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconBellOff(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconBellOff;
