// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Columns as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconColumns(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconColumns;
