// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Mic as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMic(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMic;
