// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Move as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMove(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMove;
