/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicDegensRouteImport } from './routes/_public/degens'
import { Route as PublicGamesRouteImport } from './routes/_public/games'
import { Route as PublicLeaderboardsRouteImport } from './routes/_public/leaderboards'
import { Route as PublicMintOMaticRouteImport } from './routes/_public/mint-o-matic'
import { Route as ApiDegensRouteImport } from './routes/api.degens'
import { Route as ApiLeaderboardsRouteImport } from './routes/api.leaderboards'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardDegensRouteImport } from './routes/dashboard.degens'
import { Route as DashboardGamerProfileRouteImport } from './routes/dashboard.gamer-profile'
import { Route as DashboardItemsRouteImport } from './routes/dashboard.items'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as DashboardRentalsRouteImport } from './routes/dashboard.rentals'
import { Route as VerificationIndexRouteImport } from './routes/verification.index'
import { Route as PublicDegensIndexRouteImport } from './routes/_public/degens.index'
import { Route as PublicDegensIdRouteImport } from './routes/_public/degens.$id'
import { Route as PublicGamesIndexRouteImport } from './routes/_public/games.index'
import { Route as PublicGamesCryptoWinterRouteImport } from './routes/_public/games.crypto-winter'
import { Route as PublicGamesMtGawxRouteImport } from './routes/_public/games.mt-gawx'
import { Route as PublicGamesSmashersRouteImport } from './routes/_public/games.smashers'
import { Route as PublicGamesWenGameRouteImport } from './routes/_public/games.wen-game'
import { Route as PublicLeaderboardsIndexRouteImport } from './routes/_public/leaderboards.index'
import { Route as PublicMintOMaticIndexRouteImport } from './routes/_public/mint-o-matic.index'
import { Route as DashboardItemsBurnerRouteImport } from './routes/dashboard.items.burner'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDegensRoute = PublicDegensRouteImport.update({
  id: '/degens',
  path: '/degens',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGamesRoute = PublicGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLeaderboardsRoute = PublicLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMintOMaticRoute = PublicMintOMaticRouteImport.update({
  id: '/mint-o-matic',
  path: '/mint-o-matic',
  getParentRoute: () => PublicRoute,
} as any)
const ApiDegensRoute = ApiDegensRouteImport.update({
  id: '/api/degens',
  path: '/api/degens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardsRoute = ApiLeaderboardsRouteImport.update({
  id: '/api/leaderboards',
  path: '/api/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDegensRoute = DashboardDegensRouteImport.update({
  id: '/degens',
  path: '/degens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGamerProfileRoute = DashboardGamerProfileRouteImport.update({
  id: '/gamer-profile',
  path: '/gamer-profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardItemsRoute = DashboardItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRentalsRoute = DashboardRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => DashboardRoute,
} as any)
const VerificationIndexRoute = VerificationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VerificationRoute,
} as any)
const PublicDegensIndexRoute = PublicDegensIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicDegensRoute,
} as any)
const PublicDegensIdRoute = PublicDegensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicDegensRoute,
} as any)
const PublicGamesIndexRoute = PublicGamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicGamesRoute,
} as any)
const PublicGamesCryptoWinterRoute = PublicGamesCryptoWinterRouteImport.update({
  id: '/crypto-winter',
  path: '/crypto-winter',
  getParentRoute: () => PublicGamesRoute,
} as any)
const PublicGamesMtGawxRoute = PublicGamesMtGawxRouteImport.update({
  id: '/mt-gawx',
  path: '/mt-gawx',
  getParentRoute: () => PublicGamesRoute,
} as any)
const PublicGamesSmashersRoute = PublicGamesSmashersRouteImport.update({
  id: '/smashers',
  path: '/smashers',
  getParentRoute: () => PublicGamesRoute,
} as any)
const PublicGamesWenGameRoute = PublicGamesWenGameRouteImport.update({
  id: '/wen-game',
  path: '/wen-game',
  getParentRoute: () => PublicGamesRoute,
} as any)
const PublicLeaderboardsIndexRoute = PublicLeaderboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLeaderboardsRoute,
} as any)
const PublicMintOMaticIndexRoute = PublicMintOMaticIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicMintOMaticRoute,
} as any)
const DashboardItemsBurnerRoute = DashboardItemsBurnerRouteImport.update({
  id: '/burner',
  path: '/burner',
  getParentRoute: () => DashboardItemsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification': typeof VerificationRouteWithChildren
  '/degens': typeof PublicDegensRouteWithChildren
  '/games': typeof PublicGamesRouteWithChildren
  '/leaderboards': typeof PublicLeaderboardsRouteWithChildren
  '/mint-o-matic': typeof PublicMintOMaticRouteWithChildren
  '/api/degens': typeof ApiDegensRoute
  '/api/leaderboards': typeof ApiLeaderboardsRoute
  '/dashboard/degens': typeof DashboardDegensRoute
  '/dashboard/gamer-profile': typeof DashboardGamerProfileRoute
  '/dashboard/items': typeof DashboardItemsRouteWithChildren
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/verification/': typeof VerificationIndexRoute
  '/degens/$id': typeof PublicDegensIdRoute
  '/games/crypto-winter': typeof PublicGamesCryptoWinterRoute
  '/games/mt-gawx': typeof PublicGamesMtGawxRoute
  '/games/smashers': typeof PublicGamesSmashersRoute
  '/games/wen-game': typeof PublicGamesWenGameRoute
  '/dashboard/items/burner': typeof DashboardItemsBurnerRoute
  '/degens/': typeof PublicDegensIndexRoute
  '/games/': typeof PublicGamesIndexRoute
  '/leaderboards/': typeof PublicLeaderboardsIndexRoute
  '/mint-o-matic/': typeof PublicMintOMaticIndexRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/degens': typeof ApiDegensRoute
  '/api/leaderboards': typeof ApiLeaderboardsRoute
  '/dashboard/degens': typeof DashboardDegensRoute
  '/dashboard/gamer-profile': typeof DashboardGamerProfileRoute
  '/dashboard/items': typeof DashboardItemsRouteWithChildren
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/verification': typeof VerificationIndexRoute
  '/degens/$id': typeof PublicDegensIdRoute
  '/games/crypto-winter': typeof PublicGamesCryptoWinterRoute
  '/games/mt-gawx': typeof PublicGamesMtGawxRoute
  '/games/smashers': typeof PublicGamesSmashersRoute
  '/games/wen-game': typeof PublicGamesWenGameRoute
  '/dashboard/items/burner': typeof DashboardItemsBurnerRoute
  '/degens': typeof PublicDegensIndexRoute
  '/games': typeof PublicGamesIndexRoute
  '/leaderboards': typeof PublicLeaderboardsIndexRoute
  '/mint-o-matic': typeof PublicMintOMaticIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification': typeof VerificationRouteWithChildren
  '/_public/degens': typeof PublicDegensRouteWithChildren
  '/_public/games': typeof PublicGamesRouteWithChildren
  '/_public/leaderboards': typeof PublicLeaderboardsRouteWithChildren
  '/_public/mint-o-matic': typeof PublicMintOMaticRouteWithChildren
  '/api/degens': typeof ApiDegensRoute
  '/api/leaderboards': typeof ApiLeaderboardsRoute
  '/dashboard/degens': typeof DashboardDegensRoute
  '/dashboard/gamer-profile': typeof DashboardGamerProfileRoute
  '/dashboard/items': typeof DashboardItemsRouteWithChildren
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/rentals': typeof DashboardRentalsRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/verification/': typeof VerificationIndexRoute
  '/_public/degens/$id': typeof PublicDegensIdRoute
  '/_public/games/crypto-winter': typeof PublicGamesCryptoWinterRoute
  '/_public/games/mt-gawx': typeof PublicGamesMtGawxRoute
  '/_public/games/smashers': typeof PublicGamesSmashersRoute
  '/_public/games/wen-game': typeof PublicGamesWenGameRoute
  '/dashboard/items/burner': typeof DashboardItemsBurnerRoute
  '/_public/degens/': typeof PublicDegensIndexRoute
  '/_public/games/': typeof PublicGamesIndexRoute
  '/_public/leaderboards/': typeof PublicLeaderboardsIndexRoute
  '/_public/mint-o-matic/': typeof PublicMintOMaticIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verification'
    | '/degens'
    | '/games'
    | '/leaderboards'
    | '/mint-o-matic'
    | '/api/degens'
    | '/api/leaderboards'
    | '/dashboard/degens'
    | '/dashboard/gamer-profile'
    | '/dashboard/items'
    | '/dashboard/overview'
    | '/dashboard/rentals'
    | '/dashboard/'
    | '/verification/'
    | '/degens/$id'
    | '/games/crypto-winter'
    | '/games/mt-gawx'
    | '/games/smashers'
    | '/games/wen-game'
    | '/dashboard/items/burner'
    | '/degens/'
    | '/games/'
    | '/leaderboards/'
    | '/mint-o-matic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/degens'
    | '/api/leaderboards'
    | '/dashboard/degens'
    | '/dashboard/gamer-profile'
    | '/dashboard/items'
    | '/dashboard/overview'
    | '/dashboard/rentals'
    | '/'
    | '/dashboard'
    | '/verification'
    | '/degens/$id'
    | '/games/crypto-winter'
    | '/games/mt-gawx'
    | '/games/smashers'
    | '/games/wen-game'
    | '/dashboard/items/burner'
    | '/degens'
    | '/games'
    | '/leaderboards'
    | '/mint-o-matic'
  id:
    | '__root__'
    | '/_public'
    | '/dashboard'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/verification'
    | '/_public/degens'
    | '/_public/games'
    | '/_public/leaderboards'
    | '/_public/mint-o-matic'
    | '/api/degens'
    | '/api/leaderboards'
    | '/dashboard/degens'
    | '/dashboard/gamer-profile'
    | '/dashboard/items'
    | '/dashboard/overview'
    | '/dashboard/rentals'
    | '/_public/'
    | '/dashboard/'
    | '/verification/'
    | '/_public/degens/$id'
    | '/_public/games/crypto-winter'
    | '/_public/games/mt-gawx'
    | '/_public/games/smashers'
    | '/_public/games/wen-game'
    | '/dashboard/items/burner'
    | '/_public/degens/'
    | '/_public/games/'
    | '/_public/leaderboards/'
    | '/_public/mint-o-matic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerificationRoute: typeof VerificationRouteWithChildren
  ApiDegensRoute: typeof ApiDegensRoute
  ApiLeaderboardsRoute: typeof ApiLeaderboardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/degens': {
      id: '/_public/degens'
      path: '/degens'
      fullPath: '/degens'
      preLoaderRoute: typeof PublicDegensRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/games': {
      id: '/_public/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof PublicGamesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/leaderboards': {
      id: '/_public/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof PublicLeaderboardsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/mint-o-matic': {
      id: '/_public/mint-o-matic'
      path: '/mint-o-matic'
      fullPath: '/mint-o-matic'
      preLoaderRoute: typeof PublicMintOMaticRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/degens': {
      id: '/api/degens'
      path: '/api/degens'
      fullPath: '/api/degens'
      preLoaderRoute: typeof ApiDegensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboards': {
      id: '/api/leaderboards'
      path: '/api/leaderboards'
      fullPath: '/api/leaderboards'
      preLoaderRoute: typeof ApiLeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/degens': {
      id: '/dashboard/degens'
      path: '/degens'
      fullPath: '/dashboard/degens'
      preLoaderRoute: typeof DashboardDegensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/gamer-profile': {
      id: '/dashboard/gamer-profile'
      path: '/gamer-profile'
      fullPath: '/dashboard/gamer-profile'
      preLoaderRoute: typeof DashboardGamerProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/items': {
      id: '/dashboard/items'
      path: '/items'
      fullPath: '/dashboard/items'
      preLoaderRoute: typeof DashboardItemsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rentals': {
      id: '/dashboard/rentals'
      path: '/rentals'
      fullPath: '/dashboard/rentals'
      preLoaderRoute: typeof DashboardRentalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/verification/': {
      id: '/verification/'
      path: '/'
      fullPath: '/verification/'
      preLoaderRoute: typeof VerificationIndexRouteImport
      parentRoute: typeof VerificationRoute
    }
    '/_public/degens/': {
      id: '/_public/degens/'
      path: '/'
      fullPath: '/degens/'
      preLoaderRoute: typeof PublicDegensIndexRouteImport
      parentRoute: typeof PublicDegensRoute
    }
    '/_public/degens/$id': {
      id: '/_public/degens/$id'
      path: '/$id'
      fullPath: '/degens/$id'
      preLoaderRoute: typeof PublicDegensIdRouteImport
      parentRoute: typeof PublicDegensRoute
    }
    '/_public/games/': {
      id: '/_public/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof PublicGamesIndexRouteImport
      parentRoute: typeof PublicGamesRoute
    }
    '/_public/games/crypto-winter': {
      id: '/_public/games/crypto-winter'
      path: '/crypto-winter'
      fullPath: '/games/crypto-winter'
      preLoaderRoute: typeof PublicGamesCryptoWinterRouteImport
      parentRoute: typeof PublicGamesRoute
    }
    '/_public/games/mt-gawx': {
      id: '/_public/games/mt-gawx'
      path: '/mt-gawx'
      fullPath: '/games/mt-gawx'
      preLoaderRoute: typeof PublicGamesMtGawxRouteImport
      parentRoute: typeof PublicGamesRoute
    }
    '/_public/games/smashers': {
      id: '/_public/games/smashers'
      path: '/smashers'
      fullPath: '/games/smashers'
      preLoaderRoute: typeof PublicGamesSmashersRouteImport
      parentRoute: typeof PublicGamesRoute
    }
    '/_public/games/wen-game': {
      id: '/_public/games/wen-game'
      path: '/wen-game'
      fullPath: '/games/wen-game'
      preLoaderRoute: typeof PublicGamesWenGameRouteImport
      parentRoute: typeof PublicGamesRoute
    }
    '/_public/leaderboards/': {
      id: '/_public/leaderboards/'
      path: '/'
      fullPath: '/leaderboards/'
      preLoaderRoute: typeof PublicLeaderboardsIndexRouteImport
      parentRoute: typeof PublicLeaderboardsRoute
    }
    '/_public/mint-o-matic/': {
      id: '/_public/mint-o-matic/'
      path: '/'
      fullPath: '/mint-o-matic/'
      preLoaderRoute: typeof PublicMintOMaticIndexRouteImport
      parentRoute: typeof PublicMintOMaticRoute
    }
    '/dashboard/items/burner': {
      id: '/dashboard/items/burner'
      path: '/burner'
      fullPath: '/dashboard/items/burner'
      preLoaderRoute: typeof DashboardItemsBurnerRouteImport
      parentRoute: typeof DashboardItemsRoute
    }
  }
}

interface PublicDegensRouteChildren {
  PublicDegensIdRoute: typeof PublicDegensIdRoute
  PublicDegensIndexRoute: typeof PublicDegensIndexRoute
}

const PublicDegensRouteChildren: PublicDegensRouteChildren = {
  PublicDegensIdRoute: PublicDegensIdRoute,
  PublicDegensIndexRoute: PublicDegensIndexRoute,
}

const PublicDegensRouteWithChildren = PublicDegensRoute._addFileChildren(
  PublicDegensRouteChildren,
)

interface PublicGamesRouteChildren {
  PublicGamesCryptoWinterRoute: typeof PublicGamesCryptoWinterRoute
  PublicGamesMtGawxRoute: typeof PublicGamesMtGawxRoute
  PublicGamesSmashersRoute: typeof PublicGamesSmashersRoute
  PublicGamesWenGameRoute: typeof PublicGamesWenGameRoute
  PublicGamesIndexRoute: typeof PublicGamesIndexRoute
}

const PublicGamesRouteChildren: PublicGamesRouteChildren = {
  PublicGamesCryptoWinterRoute: PublicGamesCryptoWinterRoute,
  PublicGamesMtGawxRoute: PublicGamesMtGawxRoute,
  PublicGamesSmashersRoute: PublicGamesSmashersRoute,
  PublicGamesWenGameRoute: PublicGamesWenGameRoute,
  PublicGamesIndexRoute: PublicGamesIndexRoute,
}

const PublicGamesRouteWithChildren = PublicGamesRoute._addFileChildren(
  PublicGamesRouteChildren,
)

interface PublicLeaderboardsRouteChildren {
  PublicLeaderboardsIndexRoute: typeof PublicLeaderboardsIndexRoute
}

const PublicLeaderboardsRouteChildren: PublicLeaderboardsRouteChildren = {
  PublicLeaderboardsIndexRoute: PublicLeaderboardsIndexRoute,
}

const PublicLeaderboardsRouteWithChildren =
  PublicLeaderboardsRoute._addFileChildren(PublicLeaderboardsRouteChildren)

interface PublicMintOMaticRouteChildren {
  PublicMintOMaticIndexRoute: typeof PublicMintOMaticIndexRoute
}

const PublicMintOMaticRouteChildren: PublicMintOMaticRouteChildren = {
  PublicMintOMaticIndexRoute: PublicMintOMaticIndexRoute,
}

const PublicMintOMaticRouteWithChildren =
  PublicMintOMaticRoute._addFileChildren(PublicMintOMaticRouteChildren)

interface PublicRouteChildren {
  PublicDegensRoute: typeof PublicDegensRouteWithChildren
  PublicGamesRoute: typeof PublicGamesRouteWithChildren
  PublicLeaderboardsRoute: typeof PublicLeaderboardsRouteWithChildren
  PublicMintOMaticRoute: typeof PublicMintOMaticRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDegensRoute: PublicDegensRouteWithChildren,
  PublicGamesRoute: PublicGamesRouteWithChildren,
  PublicLeaderboardsRoute: PublicLeaderboardsRouteWithChildren,
  PublicMintOMaticRoute: PublicMintOMaticRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardItemsRouteChildren {
  DashboardItemsBurnerRoute: typeof DashboardItemsBurnerRoute
}

const DashboardItemsRouteChildren: DashboardItemsRouteChildren = {
  DashboardItemsBurnerRoute: DashboardItemsBurnerRoute,
}

const DashboardItemsRouteWithChildren = DashboardItemsRoute._addFileChildren(
  DashboardItemsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardDegensRoute: typeof DashboardDegensRoute
  DashboardGamerProfileRoute: typeof DashboardGamerProfileRoute
  DashboardItemsRoute: typeof DashboardItemsRouteWithChildren
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardRentalsRoute: typeof DashboardRentalsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDegensRoute: DashboardDegensRoute,
  DashboardGamerProfileRoute: DashboardGamerProfileRoute,
  DashboardItemsRoute: DashboardItemsRouteWithChildren,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardRentalsRoute: DashboardRentalsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface VerificationRouteChildren {
  VerificationIndexRoute: typeof VerificationIndexRoute
}

const VerificationRouteChildren: VerificationRouteChildren = {
  VerificationIndexRoute: VerificationIndexRoute,
}

const VerificationRouteWithChildren = VerificationRoute._addFileChildren(
  VerificationRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerificationRoute: VerificationRouteWithChildren,
  ApiDegensRoute: ApiDegensRoute,
  ApiLeaderboardsRoute: ApiLeaderboardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
