// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { MoreVertical as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMoreVertical(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMoreVertical;
