// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Airplay as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconAirplay(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconAirplay;
