// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ShieldOff as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconShieldOff(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconShieldOff;
