/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IChildERC20 } from './IChildERC20';
export type { IERC1155SupplyUpgradeable } from './IERC1155SupplyUpgradeable';
export type { IERC20MetaTransactions } from './IERC20MetaTransactions';
export type { IERC20PresetMinterPauserUpgradeable } from './IERC20PresetMinterPauserUpgradeable';
export type { IGovToken } from './IGovToken';
export type { IMintable } from './IMintable';
export type { INiftyEquipment } from './INiftyEquipment';
export type { INiftyLaunchComics } from './INiftyLaunchComics';
export type { INiftyMarketplace } from './INiftyMarketplace';
