/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1155SupplyUpgradeable } from './IERC1155SupplyUpgradeable';
export type { IERC20PresetMinterPauserUpgradeable } from './IERC20PresetMinterPauserUpgradeable';
export type { INiftyEquipment } from './INiftyEquipment';
export type { INiftyLaunchComics } from './INiftyLaunchComics';
