// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ThumbsDown as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconThumbsDown(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconThumbsDown;
