// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { PauseCircle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconPauseCircle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconPauseCircle;
