// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ZoomOut as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconZoomOut(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconZoomOut;
