// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Italic as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconItalic(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconItalic;
