// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ToggleRight as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconToggleRight(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconToggleRight;
