// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Briefcase as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconBriefcase(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconBriefcase;
