/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20BurnableUpgradeable } from './IERC20BurnableUpgradeable';
export type { NFTLRaffle } from './NFTLRaffle';
