// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ArrowUpCircle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconArrowUpCircle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconArrowUpCircle;
