import NativeImage from '@nl/ui/custom/native-image'
import styles from './machine.module.css'

interface MachineFrameProps {
  src: string
  unoptimized?: boolean
}

/** A single static layer of the burner machine collage. */
const MachineFrame = (props: MachineFrameProps) => (
  <NativeImage
    src={props.src}
    alt={props.src}
    width={352}
    height={912}
    class={`pixelated ${styles.frame} ${styles.static}`}
    unoptimized={props.unoptimized ?? props.src.endsWith('.gif')}
  />
)

export default MachineFrame

interface SpriteFrameProps {
  /** Vertical sprite sheet generated by scripts/make-burner-sheets.mjs. */
  sheet: string
  frames: 2 | 5
  label: string
}

/**
 * Cycles a vertical sprite sheet with pure CSS steps: no interval, no image
 * re-decode churn, paused automatically under prefers-reduced-motion.
 */
export function SpriteFrame(props: SpriteFrameProps) {
  return (
    <div
      role="img"
      aria-label={props.label}
      class={`pixelated ${styles.frame} ${styles[`cycle${props.frames}`]}`}
      style={{ 'background-image': `url(${props.sheet})` }}
    />
  )
}
