// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Book as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconBook(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconBook;
