// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Edit2 as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconEdit2(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconEdit2;
