// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Tv as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTv(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTv;
