// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { PlusCircle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconPlusCircle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconPlusCircle;
