// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Underline as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconUnderline(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconUnderline;
