// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Award as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconAward(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconAward;
