// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { TrendingDown as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTrendingDown(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTrendingDown;
