// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { UserPlus as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconUserPlus(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconUserPlus;
