// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ArrowDownCircle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconArrowDownCircle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconArrowDownCircle;
