// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ChevronUp as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconChevronUp(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconChevronUp;
