// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Clipboard as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconClipboard(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconClipboard;
