// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Image as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconImage(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconImage;
