import type { Metadata, Viewport } from 'next';
import type { PropsWithChildren } from 'react';
import { customFontClassName } from '@nl/ui/fonts';
import { ThemeProvider } from '@nl/ui/custom/theme';

import '@/styles/app.css';

export const metadata: Metadata = { title: 'Create Turborepo', description: 'Generated by create turbo' };

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  themeColor: [
    { media: '(prefers-color-scheme: dark)', color: '#18181b' },
    { media: '(prefers-color-scheme: light)', color: '#fafafa' },
  ],
  colorScheme: 'dark light',
};

export default function RootLayout({ children }: PropsWithChildren): React.ReactNode {
  return (
    <html lang="en" suppressHydrationWarning className={customFontClassName}>
      <body suppressHydrationWarning>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
