// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Hexagon as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconHexagon(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconHexagon;
