// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Trash as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTrash(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTrash;
