name: Algolia Search

on:
  schedule:
    - cron: '0 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Scraper
        run: |
          brew install jq
          docker run -e "APPLICATION_ID=${{ env.ALGOLIA_APP_ID }}" -e "API_KEY=${{ env.ALGOLIA_API_KEY }}" -e "CONFIG=$(cat ./config.json | jq -r tostring)" algolia/docsearch-scraper
