// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { CornerDownRight as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCornerDownRight(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCornerDownRight;
