// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { CornerDownLeft as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCornerDownLeft(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCornerDownLeft;
