// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { RefreshCcw as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconRefreshCcw(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconRefreshCcw;
