// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Archive as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconArchive(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconArchive;
