// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Aperture as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconAperture(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconAperture;
