// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { WifiOff as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconWifiOff(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconWifiOff;
