import type { JSX } from 'solid-js'
import { imageProps } from './image-props.mjs'

declare const APP_IMAGE_MANIFEST: Record<string, { hash: string; width: number; height: number }>

type Source = string | { src: string; width?: number; height?: number }
export interface OptimizedImageProps extends Omit<JSX.ImgHTMLAttributes<HTMLImageElement>, 'src'> {
  src: Source
  priority?: boolean
  preload?: boolean
  fill?: boolean
  unoptimized?: boolean
  quality?: number
  placeholder?: 'blur' | 'empty'
  blurDataURL?: string
}

export function getOptimizedImageProps(
  props: OptimizedImageProps
): JSX.ImgHTMLAttributes<HTMLImageElement> & { src: string } {
  // The manifest is injected by the Vite `define` of the prepared build; in
  // unwired contexts (unit tests, unbundled SSR) it falls back to originals.
  const manifest = typeof APP_IMAGE_MANIFEST === 'undefined' ? {} : APP_IMAGE_MANIFEST
  return imageProps(props, manifest) as JSX.ImgHTMLAttributes<HTMLImageElement> & { src: string }
}

const preloadImage = (src: string, srcSet?: string, sizes?: string) => {
  if (typeof document === 'undefined') return
  const link = document.createElement('link')
  link.rel = 'preload'
  link.as = 'image'
  link.href = src
  link.setAttribute('fetchpriority', 'high')
  if (srcSet) link.setAttribute('imagesrcset', srcSet)
  if (sizes) link.setAttribute('imagesizes', sizes)
  document.head.appendChild(link)
}

/**
 * Renders the manifest-resolved `<img>`: build-time WebP variants with a
 * responsive `srcSet` when the source was generated by
 * `scripts/prepare-images.mjs`, the original file otherwise.
 */
export function OptimizedImage(props: OptimizedImageProps) {
  const result = getOptimizedImageProps(props)

  if ((props.priority || props.preload) && typeof result.src === 'string') {
    preloadImage(
      result.src,
      result.srcSet as string | undefined,
      result.sizes as string | undefined
    )
  }

  return <img {...result} />
}

export default OptimizedImage
