import { preload as preloadImage } from 'react-dom'
import type { ComponentProps } from 'react'
import { imageProps } from './image-props.mjs'

declare const APP_IMAGE_MANIFEST: Record<string, { hash: string; width: number; height: number }>

type Source = string | { src: string; width?: number; height?: number }
export interface OptimizedImageProps extends Omit<ComponentProps<'img'>, 'src'> {
  src: Source
  priority?: boolean
  preload?: boolean
  fill?: boolean
  unoptimized?: boolean
  quality?: number
  placeholder?: 'blur' | 'empty'
  blurDataURL?: string
}

export function getOptimizedImageProps(
  props: OptimizedImageProps
): ComponentProps<'img'> & { src: string } {
  // The manifest is injected by the Vite `define` of the prepared build; in
  // unwired contexts (unit tests, unbundled SSR) it falls back to originals.
  const manifest = typeof APP_IMAGE_MANIFEST === 'undefined' ? {} : APP_IMAGE_MANIFEST
  return imageProps(props, manifest) as ComponentProps<'img'> & { src: string }
}

/**
 * Renders the manifest-resolved `<img>`: build-time WebP variants with a
 * responsive `srcSet` when the source was generated by
 * `scripts/prepare-images.mjs`, the original file otherwise.
 */
export function OptimizedImage(props: OptimizedImageProps) {
  const result = getOptimizedImageProps(props)

  if ((props.priority || props.preload) && typeof result.src === 'string') {
    preloadImage(result.src, {
      as: 'image',
      fetchPriority: 'high',
      ...(result.srcSet ? { imageSrcSet: result.srcSet, imageSizes: result.sizes } : {}),
    })
  }

  return <img {...result} />
}

export default OptimizedImage
