// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Volume2 as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconVolume2(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconVolume2;
