// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { UploadCloud as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconUploadCloud(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconUploadCloud;
