// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ZoomIn as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconZoomIn(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconZoomIn;
