// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Share as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconShare(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconShare;
