// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Database as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconDatabase(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconDatabase;
