// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ChevronsDown as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconChevronsDown(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconChevronsDown;
