// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Repeat as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconRepeat(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconRepeat;
