export const GOOGLE_TAG_MANAGER_ID = 'GTM-MHCXVXJZ';
export const IS_DEV = process.env.NEXT_PUBLIC_VERCEL_ENV !== 'production';

export const CATEGORIES = {
  AUTH: 'Authentication',
  ECOMMERCE: 'Ecommerce',
  ENGAGEMENT: 'Engagement',
  REFERRAL: 'Product Referral',
  WEB_VITALS: 'Web Vitals',
} as const;

export type CustomEventCategories = (typeof CATEGORIES)[keyof typeof CATEGORIES];

export const EVENTS = {
  // Authentication
  LOGIN: 'login',
  LOGOUT: 'logout',
  // Ecommerce
  ADD_TO_CART: 'add_to_cart',
  BEGIN_CHECKOUT: 'begin_checkout',
  PURCHASE_COMPLETE: 'purchase',
  SPEND_VIRTUAL_CURRENCY: 'spend_virtual_currency',
  // Engagement
  SELECT_CONTENT: 'select_content',
  // Other
  GAME_REFERRAL: 'game_referral',
  WEB_VITALS: 'web_vitals',
  // Deprecated
  // TODO: cleanup custom events and use GA4 recommended events where possible
  // https://support.google.com/analytics/answer/9267735?hl=en
  DEGEN_EQUIP_ANIMATION_POSE_CLICKED: 'degen_equip_animation_pose_clicked',
  DEGEN_EQUIP_ANIMATION_ROTATE_CLICKED: 'degen_equip_animation_rotate_clicked',
  DEGEN_EQUIP_CLICKED: 'degen_equip_clicked',
  DEGEN_EQUIP_STARTED: 'degen_equip_started',
  DEGEN_EQUIP_SUCCESS: 'degen_equip_success',
  DEGEN_INVENTORY_BREAD_BAT_EQUIPPED: 'degen_inventory_bread_bat_equipped',
  DEGEN_INVENTORY_CAPE_EQUIPPED: 'degen_inventory_cape_equipped',
  DEGEN_INVENTORY_COMPANION_EQUIPPED: 'degen_inventory_companion_equipped',
  DEGEN_INVENTORY_DIAMOND_BAT_EQUIPPED: 'degen_inventory_diamond_bat_equipped',
  DEGEN_INVENTORY_HALO_EQUIPPED: 'degen_inventory_halo_equipped',
  DEGEN_INVENTORY_PURPLE_BAT_EQUIPPED: 'degen_inventory_purple_bat_equipped',
  DEGEN_SLOT_BACK_UNEQUIPPED: 'degen_slot_back_unequipped',
  DEGEN_SLOT_HEAD_UNEQUIPPED: 'degen_slot_head_unequipped',
  DEGEN_SLOT_PET_UNEQUIPPED: 'degen_slot_pet_unequipped',
  DEGEN_SLOT_WEAPON_UNEQUIPPED: 'degen_slot_weapon_unequipped',
  PLAY_ARCADE_GAMES_BUTTON_TAPPED: 'play_arcade_games_button_tapped',
  RENTAL_BUY_NFTL_CLICKED: 'rental_buy_nftl_clicked',
  RENTAL_PASS_CLICKED: 'rental_pass_clicked',
  RENTAL_RECRUIT_CLICKED: 'rental_recruit_clicked',
  RENTAL_REFRESH_BALANCE_CLICKED: 'rental_refresh_balance_clicked',
} as const;

export type CustomEventNames = (typeof EVENTS)[keyof typeof EVENTS];

export const EVENT_CATEGORIES = {
  // Authentication
  [EVENTS.LOGIN]: CATEGORIES.AUTH,
  [EVENTS.LOGOUT]: CATEGORIES.AUTH,
  // Ecommerce
  [EVENTS.ADD_TO_CART]: CATEGORIES.ECOMMERCE,
  [EVENTS.BEGIN_CHECKOUT]: CATEGORIES.ECOMMERCE,
  [EVENTS.PURCHASE_COMPLETE]: CATEGORIES.ECOMMERCE,
  [EVENTS.SPEND_VIRTUAL_CURRENCY]: CATEGORIES.ECOMMERCE,
  // Engagement
  [EVENTS.SELECT_CONTENT]: CATEGORIES.ENGAGEMENT,
  // Other
  [EVENTS.GAME_REFERRAL]: CATEGORIES.REFERRAL,
  [EVENTS.WEB_VITALS]: CATEGORIES.WEB_VITALS,
  // Deprecated
  [EVENTS.DEGEN_EQUIP_ANIMATION_POSE_CLICKED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_EQUIP_ANIMATION_ROTATE_CLICKED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_EQUIP_CLICKED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_EQUIP_STARTED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_EQUIP_SUCCESS]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_BREAD_BAT_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_CAPE_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_COMPANION_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_DIAMOND_BAT_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_HALO_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_PURPLE_BAT_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_SLOT_BACK_UNEQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_SLOT_HEAD_UNEQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_SLOT_PET_UNEQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_SLOT_WEAPON_UNEQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.PLAY_ARCADE_GAMES_BUTTON_TAPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.RENTAL_BUY_NFTL_CLICKED]: CATEGORIES.ECOMMERCE,
  [EVENTS.RENTAL_PASS_CLICKED]: CATEGORIES.ECOMMERCE,
  [EVENTS.RENTAL_RECRUIT_CLICKED]: CATEGORIES.ECOMMERCE,
  [EVENTS.RENTAL_REFRESH_BALANCE_CLICKED]: CATEGORIES.ECOMMERCE,
} as Record<CustomEventNames | (string & {}), CustomEventCategories>;
