export const GOOGLE_TAG_MANAGER_ID = 'GTM-MHCXVXJZ';
export const IS_DEV = process.env.NEXT_PUBLIC_VERCEL_ENV !== 'production';

export const CATEGORIES = {
  AUTH: 'Authentication',
  ECOMMERCE: 'Ecommerce',
  ENGAGEMENT: 'Engagement',
  GAMEPLAY: 'Gameplay',
  LEADERBOARD: 'Leaderboard',
  WEB_VITALS: 'Web Vitals',
  NEXT_CUSTOM_METRICS: 'Next.js Custom Metrics',
} as const;

export type CustomEventCategories = (typeof CATEGORIES)[keyof typeof CATEGORIES];

export const EVENTS = {
  // Authentication
  LOGIN: 'login',
  LOGOUT: 'logout',
  // Ecommerce
  ADD_TO_CART: 'add_to_cart',
  BEGIN_CHECKOUT: 'begin_checkout',
  BUY_ARCADE_TOKEN_COMPLETE: 'buy_arcade_token_complete',
  BUY_ARCADE_TOKEN_STARTED: 'buy_arcade_token_started',
  PURCHASE: 'purchase',
  RENTAL_BUY_NFTL_CLICKED: 'rental_buy_nftl_clicked',
  RENTAL_PASS_CLICKED: 'rental_pass_clicked',
  RENTAL_RECRUIT_CLICKED: 'rental_recruit_clicked',
  RENTAL_REFRESH_BALANCE_CLICKED: 'rental_refresh_balance_clicked',
  // Engagement
  DEGEN_EQUIP_ANIMATION_POSE_CLICKED: 'degen_equip_animation_pose_clicked',
  DEGEN_EQUIP_ANIMATION_ROTATE_CLICKED: 'degen_equip_animation_rotate_clicked',
  DEGEN_EQUIP_CLICKED: 'degen_equip_clicked',
  DEGEN_EQUIP_STARTED: 'degen_equip_started',
  DEGEN_EQUIP_SUCCESS: 'degen_equip_success',
  DEGEN_INVENTORY_BREAD_BAT_EQUIPPED: 'degen_inventory_bread_bat_equipped',
  DEGEN_INVENTORY_CAPE_EQUIPPED: 'degen_inventory_cape_equipped',
  DEGEN_INVENTORY_COMPANION_EQUIPPED: 'degen_inventory_companion_equipped',
  DEGEN_INVENTORY_DIAMOND_BAT_EQUIPPED: 'degen_inventory_diamond_bat_equipped',
  DEGEN_INVENTORY_HALO_EQUIPPED: 'degen_inventory_halo_equipped',
  DEGEN_INVENTORY_PURPLE_BAT_EQUIPPED: 'degen_inventory_purple_bat_equipped',
  DEGEN_SLOT_BACK_UNEQUIPPED: 'degen_slot_back_unequipped',
  DEGEN_SLOT_HEAD_UNEQUIPPED: 'degen_slot_head_unequipped',
  DEGEN_SLOT_PET_UNEQUIPPED: 'degen_slot_pet_unequipped',
  DEGEN_SLOT_WEAPON_UNEQUIPPED: 'degen_slot_weapon_unequipped',
  // Gameplay
  CRYPTO_WINTER_GAME_VIEWED: 'crypto_winter_game_viewed',
  MT_GAWX_GAME_VIEWED: 'mt_gawx_game_viewed',
  NIFTY_SMASHERS_GAME_VIEWED: 'nifty_smashers_game_viewed',
  PLAY_ARCADE_GAMES_BUTTON_TAPPED: 'play_arcade_games_button_tapped',
  WEN_GAME_VIEWED: 'wen_game_viewed',
  // Leaderboard
  CRYPTO_WINTER_LEADERBOARD_VIEWED: 'crypto_winter_leaderboard_viewed',
  LEADERBOARD_CHECK_YOUR_RANK_CLICKED_CRYPTO_WINTER: 'check_your_rank_clicked_crypto_winter',
  LEADERBOARD_CHECK_YOUR_RANK_CLICKED_MT_GAWX: 'check_your_rank_clicked_gawx',
  LEADERBOARD_CHECK_YOUR_RANK_CLICKED_SMASHERS: 'check_your_rank_clicked_smashers',
  LEADERBOARD_CHECK_YOUR_RANK_CLICKED_WEN: 'check_your_rank_clicked_wen',
  LEADERBOARD_GAME_FILTER_CHANGED: 'leaderboard_game_filter_changed',
  LEADERBOARD_TYPE_FILTER_CHANGED: 'leaderboard_type_filter_changed',
  MT_GAWX_LEADERBOARD_VIEWED: 'mt_gawx_leaderboard_viewed',
  NIFTY_SMASHERS_LEADERBOARD_VIEWED: 'nifty_smashers_leaderboard_viewed',
  WEN_GAME_LEADERBOARD_VIEWED: 'wen_game_leaderboard_viewed',
  // Web Vitals
  CLS: 'CLS',
  FCP: 'FCP',
  FID: 'FID',
  INP: 'INP',
  LCP: 'LCP',
  TTFB: 'TTFB',
  // Next.js Custom Metrics
  NEXT_HYDRATION: 'Next.js-hydration',
  NEXT_ROUTE_CHANGE_TO_RENDER: 'Next.js-route-change-to-render',
  NEXT_RENDER: 'Next.js-render',
  // Other
  GAME_REFERRAL: 'game_referral',
} as const;

export type CustomEventNames = (typeof EVENTS)[keyof typeof EVENTS];

export const EVENT_CATEGORIES = {
  // Authentication
  [EVENTS.LOGIN]: CATEGORIES.AUTH,
  [EVENTS.LOGOUT]: CATEGORIES.AUTH,
  // Ecommerce
  [EVENTS.ADD_TO_CART]: CATEGORIES.ECOMMERCE,
  [EVENTS.BEGIN_CHECKOUT]: CATEGORIES.ECOMMERCE,
  [EVENTS.BUY_ARCADE_TOKEN_COMPLETE]: CATEGORIES.ECOMMERCE,
  [EVENTS.BUY_ARCADE_TOKEN_STARTED]: CATEGORIES.ECOMMERCE,
  [EVENTS.PURCHASE]: CATEGORIES.ECOMMERCE,
  [EVENTS.RENTAL_BUY_NFTL_CLICKED]: CATEGORIES.ECOMMERCE,
  [EVENTS.RENTAL_PASS_CLICKED]: CATEGORIES.ECOMMERCE,
  [EVENTS.RENTAL_RECRUIT_CLICKED]: CATEGORIES.ECOMMERCE,
  [EVENTS.RENTAL_REFRESH_BALANCE_CLICKED]: CATEGORIES.ECOMMERCE,
  // Engagement
  [EVENTS.DEGEN_EQUIP_ANIMATION_POSE_CLICKED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_EQUIP_ANIMATION_ROTATE_CLICKED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_EQUIP_CLICKED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_EQUIP_STARTED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_EQUIP_SUCCESS]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_BREAD_BAT_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_CAPE_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_COMPANION_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_DIAMOND_BAT_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_HALO_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_INVENTORY_PURPLE_BAT_EQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_SLOT_BACK_UNEQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_SLOT_HEAD_UNEQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_SLOT_PET_UNEQUIPPED]: CATEGORIES.ENGAGEMENT,
  [EVENTS.DEGEN_SLOT_WEAPON_UNEQUIPPED]: CATEGORIES.ENGAGEMENT,
  // Gameplay
  [EVENTS.CRYPTO_WINTER_GAME_VIEWED]: CATEGORIES.GAMEPLAY,
  [EVENTS.MT_GAWX_GAME_VIEWED]: CATEGORIES.GAMEPLAY,
  [EVENTS.NIFTY_SMASHERS_GAME_VIEWED]: CATEGORIES.GAMEPLAY,
  [EVENTS.PLAY_ARCADE_GAMES_BUTTON_TAPPED]: CATEGORIES.GAMEPLAY,
  [EVENTS.WEN_GAME_VIEWED]: CATEGORIES.GAMEPLAY,
  // Leaderboard
  [EVENTS.CRYPTO_WINTER_LEADERBOARD_VIEWED]: CATEGORIES.LEADERBOARD,
  [EVENTS.LEADERBOARD_CHECK_YOUR_RANK_CLICKED_CRYPTO_WINTER]: CATEGORIES.LEADERBOARD,
  [EVENTS.LEADERBOARD_CHECK_YOUR_RANK_CLICKED_MT_GAWX]: CATEGORIES.LEADERBOARD,
  [EVENTS.LEADERBOARD_CHECK_YOUR_RANK_CLICKED_SMASHERS]: CATEGORIES.LEADERBOARD,
  [EVENTS.LEADERBOARD_CHECK_YOUR_RANK_CLICKED_WEN]: CATEGORIES.LEADERBOARD,
  [EVENTS.LEADERBOARD_GAME_FILTER_CHANGED]: CATEGORIES.LEADERBOARD,
  [EVENTS.LEADERBOARD_TYPE_FILTER_CHANGED]: CATEGORIES.LEADERBOARD,
  [EVENTS.MT_GAWX_LEADERBOARD_VIEWED]: CATEGORIES.LEADERBOARD,
  [EVENTS.NIFTY_SMASHERS_LEADERBOARD_VIEWED]: CATEGORIES.LEADERBOARD,
  [EVENTS.WEN_GAME_LEADERBOARD_VIEWED]: CATEGORIES.LEADERBOARD,
} as Record<CustomEventNames | (string & {}), CustomEventCategories>;
