// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Sliders as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconSliders(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconSliders;
