// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Watch as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconWatch(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconWatch;
