// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { MinusCircle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMinusCircle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMinusCircle;
