// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { SkipBack as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconSkipBack(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconSkipBack;
