// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Eye as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconEye(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconEye;
