// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { EyeOff as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconEyeOff(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconEyeOff;
