// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Gitlab as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconGitlab(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconGitlab;
