// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Divide as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconDivide(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconDivide;
