// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Terminal as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTerminal(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTerminal;
