// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Crosshair as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCrosshair(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCrosshair;
