// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { TrendingUp as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTrendingUp(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTrendingUp;
