/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155Permit } from './ERC1155Permit';
export type { IERC1155Permit } from './IERC1155Permit';
export type { ImmutableERC1155Base } from './ImmutableERC1155Base';
