/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc1155PermitSol from './ERC1155Permit.Sol';
export type { erc1155PermitSol };
export type { IERC1155Permit } from './IERC1155Permit';
export type { ImmutableERC1155Base } from './ImmutableERC1155Base';
