// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ArrowDown as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconArrowDown(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconArrowDown;
