// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Star as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconStar(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconStar;
