// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Tablet as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTablet(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTablet;
