// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Speaker as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconSpeaker(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconSpeaker;
