// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { StopCircle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconStopCircle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconStopCircle;
