// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { FilePlus as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconFilePlus(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconFilePlus;
