// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { DivideCircle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconDivideCircle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconDivideCircle;
