// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Pause as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconPause(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconPause;
