// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Tool as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTool(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTool;
