// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { UserMinus as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconUserMinus(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconUserMinus;
