// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ChevronDown as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconChevronDown(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconChevronDown;
