// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Triangle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconTriangle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconTriangle;
