// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { PieChart as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconPieChart(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconPieChart;
