// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ShoppingCart as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconShoppingCart(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconShoppingCart;
