// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Octagon as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconOctagon(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconOctagon;
