/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc1155PermitSol from './ERC1155Permit.Sol';
export { IERC1155Permit__factory } from './IERC1155Permit__factory';
export { ImmutableERC1155Base__factory } from './ImmutableERC1155Base__factory';
