// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { CloudLightning as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCloudLightning(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCloudLightning;
