// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { User as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconUser(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconUser;
