// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { ChevronsUp as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconChevronsUp(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconChevronsUp;
