// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { CornerRightUp as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCornerRightUp(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCornerRightUp;
