// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Square as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconSquare(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconSquare;
