// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { CloudRain as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCloudRain(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCloudRain;
