// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { AlertCircle as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconAlertCircle(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconAlertCircle;
