// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Droplet as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconDroplet(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconDroplet;
