// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Globe as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconGlobe(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconGlobe;
