// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { MapPin as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMapPin(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMapPin;
