// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Feather as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconFeather(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconFeather;
