// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Thermometer as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconThermometer(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconThermometer;
