// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Rewind as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconRewind(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconRewind;
