// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Save as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconSave(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconSave;
