// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Music as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMusic(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMusic;
