// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Clock as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconClock(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconClock;
