// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Maximize as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconMaximize(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconMaximize;
