// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { RefreshCw as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconRefreshCw(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconRefreshCw;
