// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Headphones as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconHeadphones(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconHeadphones;
