// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Code as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconCode(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconCode;
