name: Validate, lint, and test on every push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run prettier
        run: npm run format
      - name: Check linter
        run: npm run lint
      - name: Check TypeScript
        run: npm run type-check
