name: Validate, lint, and test on every push

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    name: Test & Build Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier
        run: pnpm format
      - name: Check linter
        run: pnpm lint
      - name: Check TypeScript
        run: pnpm type-check
      - name: Build
        run: pnpm build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          NEXT_PUBLIC_NETWORK: ${{ secrets.NEXT_PUBLIC_NETWORK }}
          NEXT_PUBLIC_APPLE_STORE_ID: ${{ secrets.NEXT_PUBLIC_APPLE_STORE_ID }}
          NEXT_PUBLIC_APPLE_STORE_LINK: ${{ secrets.NEXT_PUBLIC_APPLE_STORE_LINK }}
          NEXT_PUBLIC_GOOGLE_PLAY_LINK: ${{ secrets.NEXT_PUBLIC_GOOGLE_PLAY_LINK }}
          NEXT_PUBLIC_EPIC_LINK: ${{ secrets.NEXT_PUBLIC_EPIC_LINK }}
          NEXT_PUBLIC_STEAM_LINK: ${{ secrets.NEXT_PUBLIC_STEAM_LINK }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
