name: Validate, lint, and test open Pull Requests

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    name: Test & Build Code
    runs-on: ubuntu-latest
    # This concurrency setting allows multiple workflows to run at the same time,
    # as long as they are for different branches. This is useful for pull requests
    # since we want to validate them as quickly as possible.
    #
    # The `cancel-in-progress` option will cancel any existing workflows with
    # the same name and ref, so we don't end up with multiple workflows running
    # at the same time for the same branch.
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref == format('refs/heads/{0}', github.event.pull_request.base.ref) && github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    # Vercel Remote Caching with Turborepo https://vercel.com/docs/monorepos/remote-caching
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier
        run: pnpm format
      - name: Check linter
        run: pnpm lint
      - name: Check TypeScript
        run: pnpm type-check
      - name: Build
        run: pnpm build
        env:
          NEXT_PUBLIC_APPLE_STORE_ID: ${{ vars.NEXT_PUBLIC_APPLE_STORE_ID }}
          NEXT_PUBLIC_APPLE_STORE_LINK: ${{ vars.NEXT_PUBLIC_APPLE_STORE_LINK }}
          NEXT_PUBLIC_EPIC_LINK: ${{ vars.NEXT_PUBLIC_EPIC_LINK }}
          NEXT_PUBLIC_GOOGLE_PLAY_LINK: ${{ vars.NEXT_PUBLIC_GOOGLE_PLAY_LINK }}
          NEXT_PUBLIC_NETWORK: ${{ vars.NEXT_PUBLIC_NETWORK }}
          NEXT_PUBLIC_STEAM_LINK: ${{ vars.NEXT_PUBLIC_STEAM_LINK }}
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ vars.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
