name: Validate, lint, and test on every push

on: [push]

jobs:
  test:
    name: Test & Build Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [8]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run prettier
        run: pnpm format
      - name: Check linter
        run: pnpm lint
      - name: Check TypeScript
        run: pnpm type-check
      - name: Build
        run: pnpm build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID }}
          NEXT_PUBLIC_NETWORK: ${{ secrets.NEXT_PUBLIC_NETWORK }}
          NEXT_PUBLIC_APPLE_CA_STORE_LINK: ${{ secrets.NEXT_PUBLIC_APPLE_CA_STORE_LINK }}
          NEXT_PUBLIC_APPLE_STORE_LINK: ${{ secrets.NEXT_PUBLIC_APPLE_STORE_LINK }}
          NEXT_PUBLIC_GOOGLE_PLAY_LINK: ${{ secrets.NEXT_PUBLIC_GOOGLE_PLAY_LINK }}
