name: Algolia Search

on:
  # Allow to run manually
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/search.yaml'
      - 'apps/docs/**'
    branches:
      - main

jobs:
  search:
    name: Algolia Search
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run Scraper
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        working-directory: apps/docs
        run: |
          docker run \
            --env ALGOLIA_APP_ID=${ALGOLIA_APP_ID} \
            --env ALGOLIA_API_KEY=${ALGOLIA_API_KEY} \
            --env "CONFIG=$(cat config.json | jq -r tostring)" \
            algolia/docsearch-scraper
