// DO NOT EDIT
// this file is generated by /internals/populate-icons script
import { Send as Icon } from 'react-feather';
import IconBase, { IconBaseProps } from './../../IconBase';

function IconSend(props: IconBaseProps) {
  return <IconBase {...props} icon={Icon} />;
}

export default IconSend;
